spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app_test_demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&characterEncoding=utf8&characterSetResults=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl